### ISSUE TITLE
If you move it as it is, it will turn into giblets.

### ISSUE THREAD

**Issue by koteakn** [PeterNgTr/codeceptjs-rest-demo#30]
If you move it as it is, it will turn into giblets.

First of all, I got this error, but it was resolved by fixing it according to the message.
![first](https://user-images.githubusercontent.com/51088920/152901219-8a04dabb-5e13-4d71-bcd5-189d325934ed.png)

Then I get this error, but I don't know the cause.
![second](https://user-images.githubusercontent.com/51088920/152901256-04284292-23f1-483f-a787-1e84f7af3d28.png)

The all detail is
```

+ jenkins/run-tests.sh 5
Pulling image 5

> codeceptjs-rest-demo@1.0.0 api-load-test /app
> k6 run load-tests/scenario-1.js


          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

    init [----------------------------------------------------------] runner
    init [----------------------------------------------------------] options
    init [----------------------------------------------------------] executor
    init [----------------------------------------------------------]   engine
    init [----------------------------------------------------------]   collector
    init [----------------------------------------------------------]   server
  execution: local
     output: -
     script: load-tests/scenario-1.js

    duration: 6s, iterations: -
         vus: 10, max: 10

    init [----------------------------------------------------------] starting
time="2022-02-07T02:11:09Z" level=info msg=Running i=136 t=966.1861ms
time="2022-02-07T02:11:10Z" level=info msg=Running i=683 t=1.9661039s
time="2022-02-07T02:11:11Z" level=info msg=Running i=1264 t=2.9662063s
time="2022-02-07T02:11:12Z" level=info msg=Running i=1847 t=3.9660997s
time="2022-02-07T02:11:13Z" level=info msg=Running i=2431 t=4.9661117s
time="2022-02-07T02:11:14Z" level=info msg=Running i=3016 t=5.9661076s

    ✓ is status 200

time="2022-02-07T02:11:14Z" level=info msg="Test finished" i=3035 t=6.0001081s
    checks.....................: 100.00% ✓ 3035 ✗ 0   
    data_received..............: 4.2 MB  699 kB/s
    data_sent..................: 224 kB  37 kB/s
    http_req_blocked...........: avg=2.19ms   min=200ns   med=500ns   max=667ms    p(90)=700ns    p(95)=800ns   
    http_req_connecting........: avg=287.67µs min=0s      med=0s      max=89.34ms  p(90)=0s       p(95)=0s      
    http_req_duration..........: avg=17.27ms  min=13.67ms med=16.33ms max=87.72ms  p(90)=20.49ms  p(95)=22.83ms 
    http_req_receiving.........: avg=182.33µs min=62.4µs  med=154.2µs max=11.94ms  p(90)=220µs    p(95)=257.62µs
    http_req_sending...........: avg=86.5µs   min=33.9µs  med=79.5µs  max=4.74ms   p(90)=116.71µs p(95)=136.25µs
    http_req_tls_handshaking...: avg=437.35µs min=0s      med=0s      max=133.85ms p(90)=0s       p(95)=0s      
    http_req_waiting...........: avg=17ms     min=13.47ms med=16.08ms max=87.49ms  p(90)=20.14ms  p(95)=22.45ms 
    http_reqs..................: 3035    505.82422/s
    iteration_duration.........: avg=19.68ms  min=13.89ms med=16.54ms max=692.63ms p(90)=20.72ms  p(95)=23.19ms 
    iterations.................: 3035    505.82422/s
    vus........................: 10      min=10 max=10
    vus_max....................: 10      min=10 max=10

TypeScript Definitions provide autocompletion in Visual Studio Code and other IDEs
Definitions were generated in steps.d.ts
creating output directory: /app/output
TSError: ⨯ Unable to compile TypeScript:
tests/sample_test.ts(1,1): error TS2304: Cannot find name 'Feature'.
tests/sample_test.ts(3,1): error TS2304: Cannot find name 'Scenario'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)

⨯ Unable to compile TypeScript:
tests/sample_test.ts(1,1): error TS2304: Cannot find name 'Feature'.
tests/sample_test.ts(3,1): error TS2304: Cannot find name 'Scenario'.


TSError: 
    at createTSError (/app/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
Final status 0
```

**Comment by kobenguyent** [comment]
Closed as not relevant to purpose of this demo project.
